mozilla/mozdownload

mozdownload/parser.py, mozdownload/scraper.py
When we traverse directories in ftp.mozilla.org, we don't close the http connection. In urllib, at least on some platforms, when you close a connection, it will be reused. Without this, it is easy to flood ftp.mozilla.org with connections, and if you are not on Mozilla's network, ftp.mozilla.org will start returning 503 Server Too Busy errors.
=> Connection close

tests/requirements.txt
This fixes issue #293, and allows to run the tests again. When Travis shows passing tests, I will get it merged immediately.
=> Update dependencies for python packages for test environment (#293)

mozdownload/__init__.py, tests/manifest.ini, tests/test_cli.py
This fixes what appears to be the accidental removal of scraper.cli from the module __init__.py which prevents calling the module directly to perform downloads. This also adds a test to ensure that mozdownload is callable from the shell.
=> Add scraper.cli to __init__.py

mozdownload/scraper.py
This PR fixes #329 via a workaround for now.
=> Workaround for downloading files via ftp-origin-scl3.mozilla.org (#329)

mozdownload/__init__.py, mozdownload/cli.py, mozdownload/factory.py, mozdownload/scraper.py, mozdownload/treeherder.py, setup.py, tests/base_scraper/test_base_scraper.py, tests/cli/test_output.py, tests/daily_scraper/test_daily_indices.py, tests/daily_scraper/test_daily_scraper.py, tests/daily_scraper/test_invalid_branch.py, tests/daily_scraper/test_invalid_date.py, tests/direct_scraper/test_direct_scraper.py, tests/factory/test_factory_invalid_options.py, tests/release_candidate_scraper/test_release_candidate_scraper.py, tests/release_candidate_scraper/test_release_candidate_scraper_indices.py, tests/release_candidate_scraper/test_release_candidate_scraper_latest.py, tests/release_scraper/test_release_scraper.py, tests/release_scraper/test_release_scraper_latest.py, tests/remote/test_fennec.py, tests/remote/test_firefox.py, tests/remote/test_thunderbird.py, tests/tinderbox_scraper/test_invalid_date.py, tests/tinderbox_scraper/test_tinderbox_scraper.py, tests/try_scraper/test_invalid_changeset.py, tests/try_scraper/test_try_scraper.py
This will fix issue #360. Please keep in mind that remote fennec tests are currently broken because API level 11 is no longer supported. I will file a separate issue to get this fixed.
@sydvicious can you please review? Please note that I pushed individual commits so it should make it easier for you to go through the code. Thanks!
=> Improve logging and arguments handling (#360)

mozdownload/parser.py, tests/directory_parser/test_directory_parser.py, tests/mozhttpd_base_test.py, tests/remote/test_fennec.py, tests/remote/test_firefox.py, tests/remote/test_thunderbird.py, tox.ini
This PR will fix issue #368. @mjzffr can you please review it? Thanks
=> Use wptserve for unit tests (#368)

.appveyor.yml
This PR will fix issue #380. It's not ready yet for review and might need updates according to appveyor failures.
=> Add Appveyor support for running unittests on Windows (#380)

mozdownload/cli.py, tests/cli/manifest.ini, tests/cli/test_cli_arguments.py
This is the bustage fix for issue #378 and also includes a test so that we can be safe it won't happen again.
@mjzffr or @sydvicious could you please review?
=> CLI command fails due to broken argv parsing (#378)

tests/remote/test_firefox.py, tests/remote/test_thunderbird.py
This PR fixes issue #413 by just updating the versions.
=> Fix remote tests due to non-existent candidate builds (#413)

README.md, tox.ini
This PR addresses issue #398 
I encountered the same issue as mentioned. A simple workaround is to not give absolute pathnames but using `tox -- -k <keyword>`. It allows you to sidestep this issue quite easily.
=> Add {posargs} to tox.ini and explained usage in README.md (#398)

setup.py
This fixes issue #430. It allows us to be more flexible in terms of which package versions are installed. It means that we allow all minor versions which should come without API changes.
=> Bump package dependencies for more relaxed version requirements (#430)

setup.cfg
Comment only change to fix the remaining items for issue #426. I will go ahead and get it landed when tests are passing.
=> Remove left-over comment for exclusion of pycodestyle warnings of bare excepts (#426)

mozdownload/scraper.py
=> Display correct build number for candidate build (#437)

mozdownload/scraper.py, tests/cli/test_correct_scraper.py, tests/factory/test_factory_invalid_options.py, tests/factory/test_factory_scraper.py, tests/tinderbox_scraper/test_tinderbox_scraper.py
The filename for human-readable code is now prepended by the date format `YYYY-MM-DD-`
If you decide you want a different format or a universal format (e.g. all timestamps) then please let me know.
Closes #181
=> Added date to tinderbox filename when human readable date supplied (#181)

tests/base_scraper/test_base_scraper.py, tests/cli/test_cli_print_url.py, tests/daily_scraper/test_daily_indices.py, tests/daily_scraper/test_daily_scraper.py, tests/daily_scraper/test_invalid_branch.py, tests/daily_scraper/test_invalid_date.py, tests/daily_scraper/test_revision.py, tests/direct_scraper/test_direct_scraper.py, tests/directory_parser/test_directory_parser.py, tests/release_candidate_scraper/test_release_candidate_scraper.py, tests/release_candidate_scraper/test_release_candidate_scraper_indices.py, tests/release_candidate_scraper/test_release_candidate_scraper_latest.py, tests/release_scraper/test_release_scraper.py, tests/release_scraper/test_release_scraper_latest.py, tests/remote/test_fennec.py, tests/remote/test_firefox.py, tests/remote/test_thunderbird.py, tests/tinderbox_scraper/test_invalid_date_tinderbox.py, tests/tinderbox_scraper/test_revision_tinderbox.py, tests/tinderbox_scraper/test_tinderbox_scraper.py, tests/treeherder/test_api.py, tests/try_scraper/test_invalid_revision.py, tests/try_scraper/test_try_scraper.py
As suggested by @davehunt on PR #467 we can remove all of those calls.
=> Remove call to unittest.main() from all test modules (#470)

tests/remote/test_thunderbird.py
This patch will temporarily skip this test until we get back those builds, or we know they aren't shipped anymore.
=> Temporarily skip the remote daily debug thunderbird test.

requirements/tests.txt, tests/base_scraper/test_base_scraper.py, tests/conftest.py
Fixes #492 
- Adds a custom auth handler and register a route
- Overrides the `decode_basic` method of request.Authentication
-  uses the right base64 decode function and fixes the bytes/str error
- enables the auth tests
The `decode_basic` call in `request.Authentication` would fail in py3 as it uses `base64.decodestring` which expects a byte-like array. Hence overrode this to use `base64.b64decode`
wptserve==2.0 from PyPI has this issue. wptserve has since been moved to https://github.com/web-platform-tests/wpt where this has been fixed.
=> Enable auth test in test_base_scraper.py

README.md
Removed obsolete link to wiki (does it still exist somewhere?) . Also added virtualenv commands because otherwise 'python setup.py develop' fails.
For me as a beginner it was confusing why 'python setup.py develop' fails when I followed instructions. With this change, installation process for a new contributer should go smoother :)
=> Improved installation section of README

mozdownload/scraper.py, tests/release_candidate_scraper/test_release_candidate_scraper_indices.py, tests/remote/test_devedition.py
Now scraper fails when invalid build number is used instead of downloading other build
Fixes issue #445
=> Fix an issue with invalid build number for candidate scraper

setup.py
This is a fix for #609 
Please take a look and let me know.
Checked with following command
```
find . -iname '*.py' | grep -Ev 'vendor|example|doc|tools|sphinx' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
```
No deprecation warning coming.
=> Upgrade syntax of setup.py to python 3.8+

tests/remote/test_firefox.py
=> Switch remote tinderbox tests from mozilla-central to mozilla-release

requirements/tests.txt
The [LegacyVersion](https://github.com/pypa/packaging/pull/407) class has been removed and that causes problems with our code. Before we will have a fix for it lets pin the package temporarily to version 21.3.0.
I filed https://github.com/mozilla/mozdownload/issues/635 to get the underlying issue fixed.
=> Temporarily pin packaging to version 31.3.0 due to removal of LegacyVersion

requirements.txt, requirements/tests.txt
None of the tests use the packaging module but mozdownload code itself. So my patch on #636 was actually wrong and this PR fixes it.
=> Fix packaging requirement for version 21.3.0

mozdownload/scraper.py, requirements.txt, requirements/tests.txt
As packaging.LegacyVersion is gone, and packaging.Version produces too many errors, use the various version classes from mozilla_version.gecko when looking for the latest version of a supported application.
=> Replace packaging.LegacyVersion use with mozilla_version. Fixes #635

requirements.txt
We switched to mozilla-version recently for version comparison. Before the 2.0.0 release the futures package got installed as dependency which is roughly 450KB in size. Since https://github.com/mozilla-releng/mozilla-version/issues/102 is fixed, this dependency is no longer needed.
As such we should always install version 2.0.0 or later.
=> Bump minimal version of mozilla-version to 2.0.0

History.md, mozdownload/cli.py
Bumps the version number and adds changelog entries for the 1.28.0 release as covered on issue #643.
=> Release mozdownload 1.28.0

mozdownload/scraper.py, tests/daily_scraper/test_invalid_platform.py
=> Raise NotFoundError if no daily build can be found for latest build date

tests/remote/test_devedition.py
=> Move DevEdition remote tests from Firefox 60.0 to 128.0

pytest.ini, tests/conftest.py
I noticed that tests that are only using data from the local HTTP server are running very slow. After investigation it turned out that the HTTP server's shutdown method takes about 0.5s to run. I filed https://github.com/web-platform-tests/wpt/issues/46710 to get this investigated.
To workaround the issue we should use the `http` fixture per session and not per test.
=> Use "http" fixture per session to increase test runtime drasticallly

.github/workflows/release.yml, pyproject.toml
Fixes https://github.com/mozilla/mozdownload/issues/669.
Thank you for reviewing my latest pull request, and I've made improvements in the following ways:
1. `pypa/gh-action-pypi-publish@release/v1` accepts either a password or PyPI token. Utilize the token instead of the user's password also i change the variable name to `pypi_token`.
2. Added a secret variable for specifying the Python version. Referring to the documentation of  `actions/setup-python@v5` , I've set it to '3.11.9', aligning with the available Python versions for that GitHub Action.
3. Implemented the use of artifacts to transfer the 'dist' folder between jobs (actions/download-artifact@v4, actions/upload-artifact@v4).
4. Set condition for publishing, ensuring the last step succeeds, the secret is not empty, and the event …
=> Action to auto publish PyPI

.github/workflows/test.yml
Upgrading both actions based on the following message when running tests in CI:
> The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3, actions/setup-python@v4. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
=> Bump checkout and setup python actions for node.js 20

.github/dependabot.yml
Fixes #702.
Hello! This change would automatically update GitHub Actions like actions/checkout@v3 to the latest version whenever a new version is released.
If we only want to update specific GitHub actions, we can specify it like this:
```
allow:
- dependency-name: "actions/checkout"
- dependency-name: "actions/setup-python"
```
=> Update dependabot.yml to auto update github actions #702

History.md, mozdownload/cli.py
=> Release version 1.29.0

.github/workflows/release.yml
Fixed https://github.com/mozilla/mozdownload/issues/669.
With the changes the release action should be triggered when a new tag is getting created.
=> Update release action to get triggered from a new tag being created
