mozilla/mozdownload

History.md, setup.py
This PR fixes issue #282. @sydvicious if you can review please? Thanks. Maybe also test if all is working fine for your specific cases, so we can be sure we indeed fixed all the failures.
=> Release version 1.15 (#282)

.travis.yml, mozdownload/__init__.py, mozdownload/errors.py, mozdownload/scraper.py, pylama.ini, tests/base_scraper/test_base_scraper.py, tests/base_scraper/test_correct_scraper.py, tests/daily_scraper/test_daily_indices.py, tests/daily_scraper/test_daily_scraper.py, tests/daily_scraper/test_invalid_branch.py, tests/daily_scraper/test_invalid_date.py, tests/direct_scraper/test_direct_scraper.py, tests/directory_parser/test_directory_parser.py, tests/release_candidate_scraper/test_release_candidate_scraper.py, tests/release_candidate_scraper/test_release_candidate_scraper_indices.py, tests/release_scraper/test_release_scraper.py, tests/tinderbox_scraper/test_invalid_date.py, tests/tinderbox_scraper/test_tinderbox_scraper.py, tests/try_scraper/test_invalid_changeset.py
This is a follow-up PR from PR #287, which we really should get in for the 1.16 release. I simply fixed the remaining issues. @AutomatedTester can you please have a look at it?
This PR will fix #157, and #250.
=> Various Travis CI and related issues (closes #157, #250)

CONTRIBUTING.md
=> Add instructions for contribution (#310)

mozdownload/cli.py
=> Switch from optparse to argparse (#318)

README.md, mozdownload/cli.py, mozdownload/factory.py, mozdownload/scraper.py, tests/base_scraper/test_base_scraper.py, tests/daily_scraper/test_daily_indices.py, tests/daily_scraper/test_daily_scraper.py, tests/daily_scraper/test_invalid_branch.py, tests/daily_scraper/test_invalid_date.py, tests/direct_scraper/test_direct_scraper.py, tests/factory/manifest.ini, tests/factory/test_factory_invalid_options.py, tests/manifest.ini, tests/release_candidate_scraper/test_release_candidate_scraper.py, tests/release_scraper/test_release_scraper.py, tests/tinderbox_scraper/test_invalid_date.py, tests/tinderbox_scraper/test_tinderbox_scraper.py, tests/try_scraper/test_invalid_changeset.py, tests/try_scraper/test_try_scraper.py
=> Improve API and documentation (#324)

History.md, setup.py
This will fix issue #322.
@davehunt can you please review? Thanks
=> Release version 1.18 (#322)

History.md, setup.py
=> Release version 1.18.1 (#331)

mozdownload/parser.py, mozdownload/scraper.py, mozdownload/utils.py, tests/manifest.ini, tests/release_candidate_scraper/test_release_candidate_scraper.py, tests/release_candidate_scraper/test_release_candidate_scraper_indices.py, tests/remote/manifest.ini, tests/remote/test_fennec.py, tests/remote/test_firefox.py, tests/remote/test_thunderbird.py
This PR fixes issue #329. @mjzffr and @sydvicious I need this reviewed. Based on the new tests we don't need manual testing against the remote server anymore.
=> Fix parser and scraper to handle new S3 based archive.mozilla.org (#329)

History.md, setup.py
This will fix issue #336. @mjzffr and @sydvicious can you please review? Thanks.
=> Release version 1.19 (#336)

mozdownload/scraper.py
=> Update BASE_URL to https://archive.mozilla.org/pub/ (#338)

tests/base_scraper/test_base_scraper.py
@davehunt This seems to fix the failure. I'm not 100% sure it's testing what we used to test (I'm not a 100% sure what used to test either...)
=> Use webqa-ci in test_optional_authentication (#348)

mozdownload/parser.py, mozdownload/scraper.py
This PR fixes issue #353. Keep in mind that it builds on-top of PR #356.
@sydvicious or @mjzffr can one of you please review? Thanks
=> Fix accidentally match for SDK builds for release and candidate builds (#353)

mozdownload/__init__.py, mozdownload/cli.py, mozdownload/errors.py, mozdownload/factory.py, mozdownload/parser.py, mozdownload/scraper.py, mozdownload/timezones.py, mozdownload/utils.py, tests/mozhttpd_base_test.py, tests/test.py
This PR fixes issue #363. Right now it depends on the PR #361 so more commits are included as necessary. @sydvicious, when reviewing please only check the last commit. Also take into account that the Fennec remote test will still fail. I will work on a fix for issue #362 tomorrow.
=> Fix various PEP warnings (#363)

mozdownload/__init__.py, mozdownload/cli.py, mozdownload/errors.py, mozdownload/factory.py, mozdownload/parser.py, mozdownload/scraper.py, mozdownload/timezones.py, mozdownload/utils.py, setup.py
This PR will fix the failures as introduced with the other PR as landed on master. Sorry for that.
=> Fix regressions introduced by PEP8 warning fixes (#363)

mozdownload/__init__.py, mozdownload/cli.py, mozdownload/errors.py, mozdownload/factory.py, mozdownload/parser.py, mozdownload/scraper.py, mozdownload/timezones.py, mozdownload/utils.py, setup.py, tests/daily_scraper/test_daily_scraper.py, tests/data/mobile/nightly/latest-mozilla-aurora-android-api-11/fennec-40.0a2.multi.android-arm.txt, tests/data/mobile/nightly/latest-mozilla-aurora-android-api-15/fennec-46.0a2.multi.android-arm.txt, tests/data/mobile/nightly/latest-mozilla-central-android-api-15/fennec-47.0a1.multi.android-arm.txt, tests/data/mobile/nightly/latest-mozilla-central-android-api-9/fennec-41.0a1.multi.android-arm.txt, tests/data/mobile/nightly/latest-mozilla-central-android-api-9/fennec-47.0a1.multi.android-arm.txt, tests/data/mobile/nightly/latest-mozilla-central-android-x86/fennec-41.0a1.multi.android-i386.txt, tests/data/mobile/nightly/latest-mozilla-central-android-x86/fennec-47.0a1.multi.android-i386.txt, tests/remote/test_fennec.py
This PR fixes issue #362. Keep in mind that it currently depends on the changes in PR #366.
=> Add support for Fennec API level 15 (#362)

History.md, mozdownload/cli.py
This PR fixes issue #372 by bumping the version and updating the changelog.
=> Release version 1.20 (#372)

.travis.yml, tests/cli/test_correct_scraper.py, tests/factory/test_factory_scraper.py
This PR will fix issue #376. It's not ready yet and will need some tweaking.
=> Add Travis support for OS X (#376)

.travis.yml
=> Make use of Travis' container based infrastructure (#382)

History.md, mozdownload/cli.py
=> Release version 1.20.1, fixes #385

CONTRIBUTING.md
This PR will be a fix for issue #379. It adds documentation to our CONTRIBUTION.md file.
=> Update docs for bdist-wheel releases (#379)

History.md, mozdownload/cli.py
=> Release version 1.20.2 (#390)

tests/remote/test_fennec.py
=> Add date parameter to api-9 test in test_fennec.py (#404)

tests/test_cases.md
This pull request addresses issue #238 .
It's been awhile since I used git so I am quite rusty so I thought I'll take an easy one ;)
@whimboo Could you please review?
Thanks :)
=> Change branch=mozilla-central to comm-central

History.md, mozdownload/cli.py
This fixes issue #408. Given that there are no code-changes I will go ahead and release if all tests are passing.
=> Release version 1.21 (#408)

tests/base_scraper/test_base_scraper.py
=> Remove test for optional authentication (#420)

setup.cfg
The PR addresses issue #418 
I only added config data to tox.ini as described in the pylama docs ( https://github.com/klen/pylama#id16 )
I could not fully change it, so let's see if the same error persists in appveyor as before.
=> Add pylama config to tox.ini (#418)

mozdownload/scraper.py, setup.cfg, tests/remote/test_firefox.py
This PR fixes issue #428. @davehunt or @callek, could one of you please have a look?
=> Fix binary_regex for candidate/release scraper (#428)

History.md, mozdownload/cli.py
Fixes the code part of issue #433. We might still wait until early tomorrow for a possible fix on PR #416. But rebasing can be done easily.
@AutomatedTester can you please have a quick look over the changes? Thanks.
=> Release version 1.22 (#433)

mozdownload/cli.py, tests/cli/test_cli_print_url.py
Add option to print final url to standard output #344
=> added option to print url, fixes #344

History.md, mozdownload/cli.py
=> Release version 1.23 (#446)

setup.py
Port progressbar to progressbar2, luckily this requires minimal code changes as API compatibility was maintained. I had to open up a new pull request because I noticed I was working in master branch, this has not been rectified
=> Port progressbar to progressbar2.

tests/remote/test_firefox.py, tox.ini
This PR will fix issue #466 but is not ready yet. Lets see how the tests on travis will work.
=> Fix test_tinderbox_scraper for ReadTimeout exceptions

tests/remote/test_thunderbird.py
=> Enable remote tests for Thunderbird daily builds and update versions and dates

History.md, mozdownload/cli.py
=> Release version 1.24

History.md, mozdownload/cli.py
=> Release version 1.25.0 (#507)

LICENSE.txt, README.md, setup.py
=> Add MPL 2.0 licence, and reformat README for proper display

tests/base_scraper/test_base_scraper.py, tests/direct_scraper/test_direct_scraper.py
- Pytest ran from command line - Successful
- Pylint Checked
=> Convert base_scraper and direct_scraper tests to Pytest

mozdownload/scraper.py, tests/daily_scraper/test_daily_indices.py, tests/daily_scraper/test_daily_scraper.py, tests/daily_scraper/test_invalid_branch.py, tests/daily_scraper/test_invalid_date.py, tests/daily_scraper/test_revision.py
- Converting Daily Scraper from unittest to pytest
=> Convert daily_scraper tests to pytest #468

tests/cli/test_cli_arguments.py, tests/cli/test_cli_print_url.py, tests/cli/test_correct_scraper.py, tests/cli/test_output.py, tests/treeherder/test_api.py, tests/treeherder/test_api_invalid_usage.py
* Convert Cli and treeherder to pytest
* separating Class in a separate File
* Pylint Check Done on the files.
=> Convert cli and treeherder to pytest

tests/remote/test_thunderbird.py
This should be enough. I'm opening this PR from the issue branch I've created as I've interpreted the instructions from the CONTRIBUTING.md file.
=> Skip remote tests for Thunderbird tinderbox builds

tests/remote/test_fennec.py
I just removed the lines dealing with android api level 16? @whimboo Please have a look at it!
=> #565 Android api level 16 unsupported

.travis.yml
=> Fix Python 3 job on MacOS (#600)

mozdownload/scraper.py, tests/base_scraper/test_base_scraper.py
=> Replaces RequestException with NotFoundError

tests/remote/test_fenix.py
=> Add more remote tests for nightly and release versions of Fenix
